spring.application.name=trackhub
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/trackhub_db}
spring.datasource.username=${DB_USER:trackhub_user}
spring.datasource.password=${DB_PASSWORD:trackhub_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
